version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: DESA-postgres
    environment:
      POSTGRES_DB: "desa"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"