# Generated by Django 5.0.1 on 2024-02-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='value',
            field=models.CharField(default='chien', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='text',
            field=models.TextField(default='chien'),
            preserve_default=False,
        ),
    ]
